<!-- Css Styles -->
<link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/elegant-icons.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/plyr.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/nice-select.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/owl.carousel.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/slicknav.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('css/style.css')}}" type="text/css">